on: [ pull_request ]

jobs:
  test-SDL2:
    name: SDL2 build test
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - run: |
          msbuild src/src.sln
