on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows:
      - CodeQL  # Replace with your test workflow's name
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
